import { jsPDF } from 'jspdf'

export function generateClientIncidentPDF(incident) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter'
  })

  const inc = incident || {}
  const id = inc.id || 'CM-49A1'
  const service = inc.service || 'User API'
  const severity = (inc.severity || 'CRITICAL').toUpperCase()
  const status = (inc.status || 'RESOLVED').toUpperCase()
  const duration = inc.recovery_duration ? `${inc.recovery_duration.toFixed(1)}s` : '11.5s'
  const createdAt = inc.created_at ? new Date(inc.created_at).toUTCString() : new Date().toUTCString()
  const resolvedAt = inc.resolved_at ? new Date(inc.resolved_at).toUTCString() : new Date().toUTCString()
  const rootCause = inc.root_cause || {
    file: 'user_service.py',
    line: 42,
    error_type: 'TypeError',
    probable_cause: "Subscript access user['name'] on NoneType object when chaos injection forces null record in user collection",
    confidence: 0.95
  }

  // --- Background styling & Header Banner ---
  doc.setFillColor(13, 11, 20) // Deep Dark violet #0D0B14
  doc.rect(0, 0, 612, 792, 'F')

  // Top header banner
  doc.setFillColor(21, 16, 32)
  doc.rect(0, 0, 612, 105, 'F')

  doc.setDrawColor(124, 58, 237) // #7C3AED
  doc.setLineWidth(2)
  doc.line(0, 105, 612, 105)

  // Title
  doc.setTextColor(245, 243, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text('CHAOSMEDIC', 40, 48)

  doc.setFontSize(10)
  doc.setFont('courier', 'bold')
  doc.setTextColor(168, 85, 247) // #A855F7
  doc.text('AUTONOMOUS SRE INCIDENT POST-MORTEM REPORT', 40, 68)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(152, 147, 168)
  doc.text('Generated by Multi-Agent Self-Healing Engine (LangGraph + FastAPI)', 40, 84)

  // Incident ID Pill
  doc.setFillColor(38, 30, 59)
  doc.roundedRect(430, 32, 142, 42, 4, 4, 'F')
  doc.setTextColor(168, 85, 247)
  doc.setFont('courier', 'bold')
  doc.setFontSize(9)
  doc.text('INCIDENT ID', 445, 48)
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(13)
  doc.text(id, 445, 66)

  let y = 135

  // --- Section: Incident Overview Table ---
  doc.setFont('courier', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(168, 85, 247)
  doc.text('// 01. TELEMETRY & INCIDENT OVERVIEW', 40, y)
  y += 18

  doc.setFillColor(21, 16, 32)
  doc.roundedRect(40, y, 532, 85, 4, 4, 'F')
  doc.setDrawColor(38, 30, 59)
  doc.setLineWidth(1)
  doc.roundedRect(40, y, 532, 85, 4, 4, 'S')

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(152, 147, 168)

  // Row 1
  doc.text('Target Service:', 55, y + 22)
  doc.setTextColor(245, 243, 255)
  doc.text(service, 145, y + 22)

  doc.setTextColor(152, 147, 168)
  doc.text('Incident Severity:', 320, y + 22)
  doc.setTextColor(239, 68, 68) // Red
  doc.text(severity, 420, y + 22)

  // Row 2
  doc.setTextColor(152, 147, 168)
  doc.text('Initial Status:', 55, y + 42)
  doc.setTextColor(239, 68, 68)
  doc.text('HTTP 500 (CRASH)', 145, y + 42)

  doc.setTextColor(152, 147, 168)
  doc.text('Current Status:', 320, y + 42)
  doc.setTextColor(16, 185, 129) // Green
  doc.text(`${status} (HTTP 200 OK)`, 420, y + 42)

  // Row 3
  doc.setTextColor(152, 147, 168)
  doc.text('Recovery Time:', 55, y + 64)
  doc.setTextColor(16, 185, 129)
  doc.text(duration, 145, y + 64)

  doc.setTextColor(152, 147, 168)
  doc.text('Timestamp:', 320, y + 64)
  doc.setTextColor(245, 243, 255)
  doc.text(resolvedAt, 420, y + 64)

  y += 115

  // --- Section: Root Cause Analysis ---
  doc.setFont('courier', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(168, 85, 247)
  doc.text('// 02. PROBABLE ROOT CAUSE DIAGNOSIS', 40, y)
  y += 18

  doc.setFillColor(21, 16, 32)
  doc.roundedRect(40, y, 532, 90, 4, 4, 'F')
  doc.roundedRect(40, y, 532, 90, 4, 4, 'S')

  doc.setFont('courier', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(239, 68, 68)
  doc.text(`[${rootCause.error_type || 'TypeError'}] in ${rootCause.file || 'user_service.py'}:${rootCause.line || 42}`, 55, y + 22)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(245, 243, 255)
  const causeLines = doc.splitTextToSize(`Cause: ${rootCause.probable_cause || 'NoneType subscript error'}`, 500)
  doc.text(causeLines, 55, y + 38)

  doc.setFont('courier', 'bold')
  doc.setTextColor(16, 185, 129)
  doc.text(`DIAGNOSIS CONFIDENCE: ${Math.round((rootCause.confidence || 0.95) * 100)}%`, 55, y + 74)

  y += 120

  // --- Section: Recovery Plans & Sandbox Verification ---
  doc.setFont('courier', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(168, 85, 247)
  doc.text('// 03. SANDBOX VALIDATION BENCHMARKS', 40, y)
  y += 18

  doc.setFillColor(21, 16, 32)
  doc.roundedRect(40, y, 532, 110, 4, 4, 'F')
  doc.roundedRect(40, y, 532, 110, 4, 4, 'S')

  doc.setFont('courier', 'bold')
  doc.setFontSize(8.5)
  
  // Plan 01
  doc.setTextColor(16, 185, 129)
  doc.text('PLAN 01: [SELECTED & APPLIED]', 55, y + 20)
  doc.setTextColor(245, 243, 255)
  doc.setFont('helvetica', 'normal')
  doc.text('Add Defensive None-Check & Graceful Fallback — Tests: 18/18 PASS (100%) | Risk: LOW', 55, y + 32)

  // Plan 02
  doc.setFont('courier', 'bold')
  doc.setTextColor(239, 68, 68)
  doc.text('PLAN 02: [REJECTED BY VALIDATION AGENT]', 55, y + 54)
  doc.setTextColor(152, 147, 168)
  doc.setFont('helvetica', 'normal')
  doc.text('Filter None entries prior to loop — Tests: 17/18 (1 FAILED - index mismatch) | Risk: MEDIUM', 55, y + 66)

  // Plan 03
  doc.setFont('courier', 'bold')
  doc.setTextColor(239, 68, 68)
  doc.text('PLAN 03: [REJECTED BY VALIDATION AGENT]', 55, y + 88)
  doc.setTextColor(152, 147, 168)
  doc.setFont('helvetica', 'normal')
  doc.text('Try/Except wrapping with dummy user — Tests: 18/18 PASS | Risk: HIGH (Silent schema corruption)', 55, y + 100)

  y += 140

  // --- Section: Applied Code Patch Diff ---
  doc.setFont('courier', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(168, 85, 247)
  doc.text('// 04. VALIDATED CODE PATCH APPLIED', 40, y)
  y += 18

  doc.setFillColor(15, 12, 24)
  doc.roundedRect(40, y, 532, 90, 4, 4, 'F')
  doc.roundedRect(40, y, 532, 90, 4, 4, 'S')

  doc.setFont('courier', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(239, 68, 68)
  doc.text("--- a/demo-app/app/user_service.py (Line 42)", 55, y + 20)
  doc.text("- formatted_name = user['name'].upper()", 55, y + 34)

  doc.setTextColor(16, 185, 129)
  doc.text("+++ b/demo-app/app/user_service.py (Line 42)", 55, y + 50)
  doc.text("+ if user is None:", 55, y + 62)
  doc.text("+     return {'id': 0, 'name': 'UNKNOWN', 'email': 'unknown@domain.com', 'role': 'guest'}", 55, y + 74)

  y += 115

  // --- Bottom Footer Seal ---
  doc.setFillColor(21, 16, 32)
  doc.roundedRect(40, y, 532, 35, 4, 4, 'F')
  doc.setFont('courier', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(16, 185, 129)
  doc.text('AUTONOMOUS RECOVERY VERIFIED: SERVICE HEALTH 100% | MEMORY STORED', 65, y + 22)

  return doc
}
